### PR TITLE
Internal Errror

### LINKED ISSUE #66: 'Water empty' shown when there is an actual error
When all 3 warning lights are blinking (including the water tank empty one)
the status shows 'Water Empty'
but all 3 blinking at the same time means error.

I still don't know exactly what error I have, I need to powercycle to fix this. 
not sure if I can grep any debug information to provide some help.

(the error is not caused by the integration as I have seen this one a couple of times in the week before I installed this one)

### PR DESCRIPTION
**Pull request by bkbartk**
add internal error message

Close #66

### CODE REVIEW

**Comment by bkbartk** [comment]
@TillFleisch 
would you please be so kind to review my PR?
I know there are a lot of commits, but in the end the change is rather small.

**Comment by TillFleisch** [comment]
Will do. I'm currently very time constraint, therefore a little patience will be necessary. (This is one of my free time projects and therefore it's not that high on my priority list :/)

After a quick glace I can say the following:
- The internal error state constants contain a trailing white space, they should not
- Is there a reason for moving the warning if-block? 
- Were you able to verify this is working as intended on your machine?

**Comment by bkbartk** [comment]
thnx,
1. I removed the trailing space, Didn't notice that you. You might want to check the German and Italian translations, those come from Google Translate.
2. the reason here is that for me it makes more sense to catch the warning light first. if for some reason the warning turns on icw any other light a warning is shown instead of the status of the other light.
3. Yes I was and it worked, After that I did some cleaning of the whole mechanism including the brewer and till now the error didn't show anymore. So I was able to test but I won't be able to test it again.

**Review by TillFleisch — APPROVED** [review]

**Comment by TillFleisch** [comment]
Thank you @bkbartk for adding this! :)

**Pull request merged**
